<?php

/**
 * @file
 * Primary module hooks for Perec Builder module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function perec_builder_theme(): array {
  return [
    'tour' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for tour templates.
 *
 * Default template: tour.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the tour information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_tour(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function perec_builder_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish tours.
      $storage = \Drupal::entityTypeManager()->getStorage('tour');
      $tour_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($tour_ids) as $tour) {
        $tour->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize tours.
      $storage = \Drupal::entityTypeManager()->getStorage('tour');
      $tour_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($tour_ids) as $tour) {
        $tour->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function perec_builder_user_predelete(UserInterface $account): void {
  // Delete tours that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('tour');
  $tour_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($tour_ids)
  );
}
